### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by tanshy17** [zjujdj/IGN#1]
非常感谢您分享关于DTI预测的代码。在复现测试的过程遇到问题RuntimeError: CUDA error: no kernel image is available for execution on the device。好像是cuda和pytorch版本不对应的报错
下面是我的运行环境配置：
cudatoolkit               10.2.89 
dgl                           0.4.3post2            
dgl-cuda10.2           0.4.3post2             
dgllife                       0.2.6  
python                    3.7.11 
pytorch                   1.7.0 

您提供的google网盘的dgl下载国内下载到一半总是报错。可否能提供百度网盘或其他下载方式？非常感谢

**Comment by tanshy17** [comment]
您使用的dgl版本是否是0.4.3？cuda==11.0？期待您的回复

**Comment by zjujdj** [comment]
dgl-cu90==0.4.3.post2 这是我用的版本

**Comment by zjujdj** [comment]
@tanshy17 

link：https://pan.baidu.com/s/1mSHNtiiqtM495Wk1w-PaWw 
code：z41f 
hello, this is the shared packaged file using baidu cloud. I guess you can produce the conda environment i used using this file.

**Comment by tanshy17** [comment]
第一次尝试用的是您提供的conda_package.txt文件，也是用的dgl-cu90==0.4.3，但是也报RuntimeError: CUDA error: no kernel image is available for execution on the device的错误，所以后面尝试用的dgl-cuda10.2，也会报同样的错误。
非常感谢您提供的文件，我试试

**Comment by zjujdj** [comment]
@tanshy17 
我觉得很有可能是你的GPU配置出问题了

**Comment by tanshy17** [comment]
特别感谢，问题解决了~在3090和3080上都会报no kernel image is available for execution on the device的错误。1660ti上可以正常运行，不会报错

**Comment by BattlePuppy** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
afterhill, @mikehotel, @hide2, @rthorpe, @nulldataset, @KyleTang, @whosexx, @vae520283995, @patrickocoffeyo, @Xerosigma, @Asta1986, @sbedell, @zerotask17, @atmos1001, @ClaudeLiang, @wmcmurray, @degjeg, @mrtavat, @OrdinaryCarrot16, @Teqqles, @PJGitHub10, @degan, @SuperSkidder, @edward-tes, @autumn84, @brucewillis88, @polluxx, @ruralant, @BunsDev, @qprimed, @coid, @originated, @0x00031337, @custompointofview, @nieldm, @iongchun, @detizzled, @synsun, @Halama, @Mayankvlog, @moondisco, @r-o-g-e-r-y-a-n-g, @faint32, @qinix, @takuan-osho, @seven1oe, @xmotomatt, @yanpozka, @indrajithbandara, @daann1lWillKre, @hardcpp, @vinceramcesoliveros, @sawatani-stone, @WalaceProstituto, @ykymd, @cwsamuelson, @supersonicclay, @WorldofOpenDev, @nanoac, @HiTECNOLOGYs, @brycedev, @harmankang, @makevoid, @luokailiang, @daxxog, @skyz319, @hugomarquez, @Jonovono, @gonsuke, @xiaoleigua, @jake100, @gpearson100, @ethanliew, @daraosn, @lai3d, @1688apps, @vdt, @davinian, @Drinkler, @Swaagie, @KleeTaurus, @CaptThomas, @raizor, @alixaxel, @Meler-Andy, @jordaniellis, @deveopsgenuis, @bsquidwrd, @jsuper, @nukesk3, @andrewerrico, @fkztw, @rictorres, @juliandavidmr, @harrywynnwill, @alexpablo, @TheKhanj, @Oziomajnr, @kseoRacZo, @jeongyy, @kevinmgyu, @xoan, @thomasplevy, @darshil, @wgiger, @zfarbp, @Trogdor23c, @lxm1117, @YingCGooi, @ajacquelin, @Cxihu, @AbhiAgarwal, @elimisteve, @ionaryu, @adamtache, @seanblonien, @mervinchan, @caihua, @teredin, @ygalvao, @corstian, @justyns, @manuasir, @blakejakopovic, @c0c41n3, @dwongdev, @timothyklim, @coinnotifications, @joeZheng3, @lokgie, @waar19, @kdbcinco, @ttimot24, @marcuswikstrom, @abood3lessa, @lux10n, @Skparab1, @dzhshf, @vivekpn, @liquidzym, @rkoichi, @sTorro, @bmjjr, @tdawger, @themeadery, @ReisMiner, @mi6e4ka, @kakaLQY
